INSERT INTO TP_DESPESA (ID, NOME, CODIGO_DESPESA)
                VALUES (1, 'CAIXA', 'C[CA]-');
INSERT INTO TP_DESPESA (ID, NOME, CODIGO_DESPESA)
                VALUES (2, 'MRV', 'C[MR]-');
INSERT INTO TP_DESPESA (ID, NOME, CODIGO_DESPESA)
                VALUES (3, 'IPTU', 'C[IPTU]-');
INSERT INTO TP_DESPESA (ID, NOME, CODIGO_DESPESA)
                VALUES (4, 'FACULDADE ( MENSALIDADE )', 'F[ME]-');
INSERT INTO TP_DESPESA (ID, NOME, CODIGO_DESPESA)
                VALUES (5, 'PRISCILA', 'C[AC]-');
INSERT INTO TP_DESPESA (ID, NOME, CODIGO_DESPESA)
                VALUES (6, 'NUBANK ( CARTÃO DE CRÉDITO )', 'C[CD]-');
INSERT INTO TP_DESPESA (ID, NOME, CODIGO_DESPESA)
                VALUES (7, 'SANTANDER ( CARTÃO DE CRÉDITO )', 'C[CD]-');
INSERT INTO TP_DESPESA (ID, NOME, CODIGO_DESPESA)
                VALUES (8, 'INTERNET', 'C[IT]-');
INSERT INTO TP_DESPESA (ID, NOME, CODIGO_DESPESA)
                VALUES (9, 'CARREFOUR ( CARTÃO DE CRÉDITO )', 'C[CD]-');
INSERT INTO TP_DESPESA (ID, NOME, CODIGO_DESPESA)
                VALUES (10, 'CASAS BAHIA ( CARTÃO DE CRÉTIDO )', 'C[CD]-');
INSERT INTO TP_DESPESA (ID, NOME, CODIGO_DESPESA)
                VALUES (11, 'COLETA', '[IG]-');
INSERT INTO TP_DESPESA (ID, NOME, CODIGO_DESPESA)
                VALUES (12, 'CARRO', 'C[CR]-');
INSERT INTO TP_DESPESA (ID, NOME, CODIGO_DESPESA)
                VALUES (13, 'ACADEMIA', 'C[AC]-');
INSERT INTO TP_DESPESA (ID, NOME, CODIGO_DESPESA)
                VALUES (14, 'CASAL', 'C[CASAL]-');
INSERT INTO TP_DESPESA (ID, NOME, CODIGO_DESPESA)
                VALUES (15, 'OUTRAS DESPESAS', 'D[OUT]-');
INSERT INTO TP_DESPESA (ID, NOME, CODIGO_DESPESA)
                VALUES (16, 'OPERACIONAL', 'D[OP]-');

COMMIT WORK;
